import type { ModuleRegistry } from "../modules/registry.js";
import type { PlatformModule } from "../modules/types.js";
import { resolveEffectiveModules } from "../product/resolve-modules.js";
import type { ProductDefinition } from "../product/types.js";
import type { ValidationResult } from "../shared/validation.js";
import type { PlannedFile, ProjectPlan } from "./types.js";

export interface BootstrapOptions {
  /** Import specifier convention for the platform package this product depends on. Defaults to "@platform/engines". */
  platformPackage?: string;
}

function buildPackageJson(definition: ProductDefinition, modules: PlatformModule[]): string {
  return JSON.stringify(
    {
      name: definition.name,
      version: "0.1.0",
      private: true,
      description: definition.description ?? `A ${definition.type} product built on the platform factory.`,
      type: "module",
      scripts: {
        dev: "tsx src/index.ts",
        build: "tsc -p tsconfig.json",
        test: "vitest run",
      },
      dependencies: {
        "@platform/engines": "workspace:*",
      },
      platformModules: modules.map((m) => m.id),
    },
    null,
    2,
  );
}

function buildReadme(definition: ProductDefinition, modules: PlatformModule[]): string {
  const moduleList = modules.map((m) => `- **${m.name}** (\`${m.id}\`) — ${m.description}`).join("\n");
  return [
    `# ${definition.name}`,
    "",
    definition.description ?? `A ${definition.type} product generated by the Universal SaaS Factory.`,
    "",
    "## Configuration",
    "",
    `- Type: \`${definition.type}\``,
    `- Auth mode: \`${definition.authMode}\``,
    `- Billing mode: \`${definition.billingMode}\``,
    `- Teams enabled: \`${definition.teamsEnabled}\``,
    `- AI enabled: \`${definition.aiEnabled}\``,
    `- Feature flags enabled: \`${definition.featureFlagsEnabled}\``,
    `- Storage enabled: \`${definition.storageEnabled}\``,
    "",
    "## Platform modules",
    "",
    moduleList || "_No platform modules resolved._",
    "",
    "## Getting started",
    "",
    "```bash",
    "npm install",
    "npm run dev",
    "```",
    "",
  ].join("\n");
}

function buildEnvExample(definition: ProductDefinition): string {
  const lines = [`# ${definition.name} — environment configuration`, "NODE_ENV=development", "PORT=3000"];
  if (definition.authMode !== "none") lines.push("SESSION_SECRET=");
  if (definition.aiEnabled) lines.push("AI_PROVIDER_API_KEY=");
  if (definition.storageEnabled) lines.push("STORAGE_BUCKET=");
  return lines.join("\n") + "\n";
}

function buildIndexTs(modules: PlatformModule[], platformPackage: string): string {
  const imports = modules
    .map((m) => `import * as ${toIdentifier(m.id)} from "${platformPackage}/${m.id}/index.js";`)
    .join("\n");
  const uses = modules.map((m) => `  ${toIdentifier(m.id)}, // ${m.description}`).join("\n");
  return [
    "// Generated by the Universal SaaS Factory bootstrap system.",
    "// Every import below reuses an existing platform module — nothing here is copied.",
    imports || "// (no platform modules resolved for this product)",
    "",
    "export const platformModules = {",
    uses,
    "};",
    "",
  ].join("\n");
}

function toIdentifier(id: string): string {
  return id.replace(/-([a-z])/g, (_match, letter: string) => letter.toUpperCase());
}

function buildModuleManifest(order: string[]): string {
  return JSON.stringify({ generatedAt: new Date().toISOString(), moduleOrder: order }, null, 2);
}

/**
 * Turns a validated `ProductDefinition` into a `ProjectPlan`: a description
 * of the files a new product repo should start with, wiring in whichever
 * platform modules it needs — computed, never hardcoded to one product.
 * Planning is pure (no disk I/O); pass the result to a `ProjectWriter` to
 * materialize it.
 */
export class ProductBootstrapper {
  plan(
    definition: ProductDefinition,
    registry: ModuleRegistry,
    options: BootstrapOptions = {},
  ): ValidationResult<ProjectPlan> {
    const platformPackage = options.platformPackage ?? "@platform/engines";
    const effectiveModuleIds = resolveEffectiveModules(definition);
    const { order, validation } = registry.resolveRequired(effectiveModuleIds);

    if (!validation.valid) {
      return {
        valid: false,
        issues: validation.issues.map((issue) => ({ path: issue.nodeId, message: issue.detail })),
      };
    }

    const modules = order.map((id) => registry.get(id)).filter((m): m is PlatformModule => m !== undefined);

    const files: PlannedFile[] = [
      { path: "package.json", content: buildPackageJson(definition, modules) },
      { path: "README.md", content: buildReadme(definition, modules) },
      { path: ".env.example", content: buildEnvExample(definition) },
      { path: "src/index.ts", content: buildIndexTs(modules, platformPackage) },
      { path: "platform-modules.json", content: buildModuleManifest(order) },
    ];

    const directories = [...new Set(files.map((f) => f.path.split("/").slice(0, -1).join("/")).filter(Boolean))];

    return {
      valid: true,
      value: { productName: definition.name, directories, files, moduleOrder: order },
    };
  }
}
