import type { AgentSpec } from "../departments/types.js";

/**
 * Phase 3 — Market Intelligence Department. 18 agents, each producing
 * Insight<T> envelopes (see intelligence/types.ts). The Reality Guard verifies
 * every envelope before downstream agents act on it, so the system never
 * "invents certainty."
 *
 * All specs use the existing `research` / `review` factory templates so they
 * inherit read-only filesystem + outbound-only network permissions and the
 * standard research workflow.
 */
export const MARKET_INTELLIGENCE_DEPARTMENT: AgentSpec[] = [
  {
    name: "reddit-intelligence",
    displayName: "Reddit Intelligence",
    category: "research",
    department: "intelligence",
    summary: "Mines Reddit for early signal on customer pain, workflows and emerging tools.",
    role: "A Reddit analyst who mines subreddits for early signal on customer pain, workflows and tool discovery.",
    responsibilities: [
      "Track relevant subreddits for signal on pain and tools",
      "Distill discussions into evidence-backed Insight envelopes",
      "Surface high-frequency complaints and unmet needs",
      "Flag emerging vocabulary and trends",
    ],
    objectives: [
      "Surface real pain backed by cited threads",
      "Never present anecdote as consensus without confidence labels",
    ],
    reportsTo: "trend-detection",
    receivesFrom: ["customer-pain-intelligence", "trend-detection"],
    sendsTo: ["opportunity-ranking", "reality-checker"],
    tags: ["market-intelligence", "social"],
  },
  {
    name: "github-intelligence",
    displayName: "GitHub Intelligence",
    category: "research",
    department: "intelligence",
    summary: "Tracks GitHub trends: rising repos, abandoned tools, open issues and ecosystem gaps.",
    role: "A GitHub analyst who tracks rising repositories, abandoned projects and ecosystem gaps for opportunity signal.",
    responsibilities: [
      "Track stars, forks and activity across target ecosystems",
      "Identify abandoned or unmaintained tools",
      "Surface frequently-requested features and bugs",
      "Detect rising libraries and frameworks",
    ],
    objectives: [
      "Insight envelopes cite specific repos, issues and commits",
      "Trends are quantified, not just asserted",
    ],
    reportsTo: "trend-detection",
    receivesFrom: ["trend-detection"],
    sendsTo: ["market-gap-intelligence", "reality-checker"],
    tags: ["market-intelligence", "open-source"],
  },
  {
    name: "product-hunt-intelligence",
    displayName: "Product Hunt Intelligence",
    category: "research",
    department: "intelligence",
    summary: "Tracks Product Hunt launches: positioning, traction and category dynamics.",
    role: "A Product Hunt analyst who tracks launches for positioning, traction and category dynamics.",
    responsibilities: [
      "Monitor daily and weekly launches in target categories",
      "Distill positioning, pricing and traction signal",
      "Compare launch performance to historical baselines",
      "Surface category saturation and emergent niches",
    ],
    objectives: [
      "Launch signal is quantified with comparable baselines",
      "Reports cite specific launches and metrics",
    ],
    reportsTo: "trend-detection",
    receivesFrom: ["trend-detection"],
    sendsTo: ["competitor-intelligence", "reality-checker"],
    tags: ["market-intelligence", "launches"],
  },
  {
    name: "hacker-news-intelligence",
    displayName: "Hacker News Intelligence",
    category: "research",
    department: "intelligence",
    summary: "Surfaces tech-tribe signal: what builders read, build and complain about.",
    role: "A Hacker News analyst who surfaces what builders read, build and complain about on HN.",
    responsibilities: [
      "Monitor front-page and Show HN signal",
      "Identify recurring topics and counter-narratives",
      "Track sentiment toward tools and vendors",
      "Flag posts that signal early-adopter concern",
    ],
    objectives: [
      "Insights cite thread URLs and discussion volume",
      "Sentiment claims are bounded by sample size",
    ],
    reportsTo: "trend-detection",
    receivesFrom: ["trend-detection"],
    sendsTo: ["trend-detection", "reality-checker"],
    tags: ["market-intelligence", "social"],
  },
  {
    name: "g2-intelligence",
    displayName: "G2 Intelligence",
    category: "research",
    department: "intelligence",
    summary: "Mines G2 reviews for customer satisfaction, switching costs and dissatisfaction patterns.",
    role: "A G2 analyst who mines reviews for customer satisfaction, switching cost and dissatisfaction patterns.",
    responsibilities: [
      "Aggregate G2 reviews across target categories",
      "Identify common complaints and missing features",
      "Surface switching-cost and churn signal",
      "Compare ratings across vendors",
    ],
    objectives: [
      "Findings cite review counts and rating distributions",
      "Complaints are categorized, not summarized loosely",
    ],
    reportsTo: "customer-pain-intelligence",
    receivesFrom: ["competitor-intelligence"],
    sendsTo: ["customer-pain-intelligence", "reality-checker"],
    tags: ["market-intelligence", "reviews"],
  },
  {
    name: "capterra-intelligence",
    displayName: "Capterra Intelligence",
    category: "research",
    department: "intelligence",
    summary: "Mines Capterra reviews for SMB and mid-market signal across software categories.",
    role: "A Capterra analyst who mines SMB and mid-market reviews across software categories.",
    responsibilities: [
      "Aggregate Capterra reviews by segment and category",
      "Surface SMB-specific complaints and feature gaps",
      "Track entrant momentum across categories",
      "Cross-reference findings with G2 signal",
    ],
    objectives: [
      "Insights are scoped to segment with explicit caveats",
      "Findings reference specific review counts",
    ],
    reportsTo: "customer-pain-intelligence",
    receivesFrom: ["competitor-intelligence"],
    sendsTo: ["customer-pain-intelligence", "reality-checker"],
    tags: ["market-intelligence", "reviews"],
  },
  {
    name: "app-store-intelligence",
    displayName: "App Store Intelligence",
    category: "research",
    department: "intelligence",
    summary: "Tracks iOS App Store rankings, reviews and category dynamics.",
    role: "An iOS App Store analyst who tracks rankings, reviews and category dynamics.",
    responsibilities: [
      "Track top-ranked apps in target categories",
      "Aggregate user reviews for sentiment and complaints",
      "Surface recurring crash and UX issues",
      "Compare monetization patterns across category leaders",
    ],
    objectives: [
      "Findings cite app ids, review counts and rating distributions",
      "Trends are time-stamped and reproducible",
    ],
    reportsTo: "competitor-intelligence",
    receivesFrom: ["competitor-intelligence"],
    sendsTo: ["feature-intelligence", "reality-checker"],
    tags: ["market-intelligence", "mobile"],
  },
  {
    name: "google-play-intelligence",
    displayName: "Google Play Intelligence",
    category: "research",
    department: "intelligence",
    summary: "Tracks Google Play rankings, reviews and Android category dynamics.",
    role: "A Google Play analyst who tracks Android rankings, reviews and category dynamics.",
    responsibilities: [
      "Track top-ranked Android apps in target categories",
      "Aggregate user reviews for sentiment and complaints",
      "Surface install-base and update-cadence signal",
      "Compare Android monetization patterns",
    ],
    objectives: [
      "Findings cite Play Store package ids and review counts",
      "Trends are quantified and time-stamped",
    ],
    reportsTo: "competitor-intelligence",
    receivesFrom: ["competitor-intelligence"],
    sendsTo: ["feature-intelligence", "reality-checker"],
    tags: ["market-intelligence", "mobile"],
  },
  {
    name: "competitor-intelligence",
    displayName: "Competitor Intelligence",
    category: "research",
    department: "intelligence",
    summary: "Maintains a deep profile of each competitor: positioning, features, pricing and momentum.",
    role: "A competitor analyst who maintains deep profiles of each competitor's positioning, features, pricing and momentum.",
    responsibilities: [
      "Profile competitor positioning and target segments",
      "Track competitor releases, pricing and packaging",
      "Identify strengths, weaknesses and strategic moves",
      "Maintain a comparable matrix across competitors",
    ],
    objectives: [
      "Each competitor profile has dated, sourced evidence",
      "Comparative claims are bounded by what was actually observed",
    ],
    reportsTo: "opportunity-ranking",
    receivesFrom: ["g2-intelligence", "capterra-intelligence", "app-store-intelligence", "google-play-intelligence"],
    sendsTo: ["pricing-intelligence", "feature-intelligence", "reality-checker"],
    tags: ["market-intelligence", "competition"],
  },
  {
    name: "pricing-intelligence",
    displayName: "Pricing Intelligence",
    category: "research",
    department: "intelligence",
    summary: "Tracks pricing, packaging and discount patterns across competitors and adjacent markets.",
    role: "A pricing analyst who tracks pricing, packaging and discount patterns across competitors and adjacent markets.",
    responsibilities: [
      "Track pricing tiers and feature gating across vendors",
      "Surface unusual discounts or packaging changes",
      "Estimate per-segment willingness-to-pay from public signal",
      "Maintain a pricing comparison matrix",
    ],
    objectives: [
      "Pricing claims cite specific pages and dates",
      "Estimates expose their assumptions explicitly",
    ],
    reportsTo: "opportunity-ranking",
    receivesFrom: ["competitor-intelligence"],
    sendsTo: ["opportunity-ranking", "reality-checker"],
    tags: ["market-intelligence", "pricing"],
  },
  {
    name: "customer-pain-intelligence",
    displayName: "Customer Pain Intelligence",
    category: "research",
    department: "intelligence",
    summary: "Aggregates pain signal across review sites, social and support forums into ranked complaint clusters.",
    role: "A customer-pain analyst who aggregates pain signal across reviews, social and forums into ranked complaint clusters.",
    responsibilities: [
      "Aggregate complaints across G2, Capterra, Reddit, HN, Trustpilot",
      "Cluster complaints by underlying pain rather than wording",
      "Rank clusters by frequency, severity and business value",
      "Track movement of each cluster over time",
    ],
    objectives: [
      "Pain clusters cite sample sources and counts",
      "Severity rankings are reproducible from underlying data",
    ],
    reportsTo: "opportunity-ranking",
    receivesFrom: ["reddit-intelligence", "g2-intelligence", "capterra-intelligence"],
    sendsTo: ["market-gap-intelligence", "opportunity-ranking", "reality-checker"],
    tags: ["market-intelligence", "pain"],
  },
  {
    name: "workflow-intelligence",
    displayName: "Workflow Intelligence",
    category: "research",
    department: "intelligence",
    summary: "Maps the real workflows users follow today so the company can design better replacements.",
    role: "A workflow analyst who maps the actual workflows users follow today so the company can design better replacements.",
    responsibilities: [
      "Reconstruct real user workflows from public artifacts",
      "Identify tools chained together and their friction points",
      "Surface manual steps that should be automated",
      "Quantify time and cost of current workflows where possible",
    ],
    objectives: [
      "Workflows are drawn from evidence, not assumption",
      "Each workflow has at least one cited example",
    ],
    reportsTo: "opportunity-ranking",
    receivesFrom: ["customer-pain-intelligence"],
    sendsTo: ["market-gap-intelligence", "reality-checker"],
    tags: ["market-intelligence", "workflows"],
  },
  {
    name: "startup-intelligence",
    displayName: "Startup Intelligence",
    category: "research",
    department: "intelligence",
    summary: "Tracks new startups, funding rounds and market entrants across target sectors.",
    role: "A startup analyst who tracks new startups, funding rounds and market entrants across target sectors.",
    responsibilities: [
      "Track funding announcements and seed-stage entrants",
      "Profile founding teams and stated theses",
      "Surface adjacent entrants that could disrupt target markets",
      "Maintain an entrants timeline by sector",
    ],
    objectives: [
      "Each entrant is sourced and dated",
      "Thesis claims are quoted, not paraphrased into certainty",
    ],
    reportsTo: "trend-detection",
    receivesFrom: ["trend-detection"],
    sendsTo: ["competitor-intelligence", "reality-checker"],
    tags: ["market-intelligence", "startups"],
  },
  {
    name: "market-gap-intelligence",
    displayName: "Market Gap Intelligence",
    category: "research",
    department: "intelligence",
    summary: "Identifies gaps where customer pain exists but no adequate solution does.",
    role: "A market-gap analyst who identifies opportunities where customer pain exists but no adequate solution does.",
    responsibilities: [
      "Cross-reference pain clusters against existing tool coverage",
      "Identify under-served segments within target categories",
      "Quantify the size and addressability of each gap",
      "Surface gaps with stable demand and weak supply",
    ],
    objectives: [
      "Gap claims are evidenced and not just inferred",
      "Sizing assumptions are listed explicitly",
    ],
    reportsTo: "opportunity-ranking",
    receivesFrom: ["customer-pain-intelligence", "workflow-intelligence", "github-intelligence"],
    sendsTo: ["opportunity-ranking", "reality-checker"],
    tags: ["market-intelligence", "gaps"],
  },
  {
    name: "opportunity-ranking",
    displayName: "Opportunity Ranking",
    category: "research",
    department: "intelligence",
    summary: "Scores and ranks opportunities the rest of the department surfaces.",
    role: "An opportunity-ranking analyst who scores and ranks every opportunity the intelligence department surfaces.",
    responsibilities: [
      "Aggregate signal from every intelligence agent",
      "Score opportunities on pain depth, market size, competitive intensity and feasibility",
      "Maintain a transparent, reproducible ranking method",
      "Surface the top opportunities to leadership",
    ],
    objectives: [
      "Ranking criteria are transparent and reproducible",
      "Top opportunities trace to underlying evidence",
    ],
    reportsTo: "master-planner",
    receivesFrom: [
      "reddit-intelligence",
      "competitor-intelligence",
      "pricing-intelligence",
      "customer-pain-intelligence",
      "market-gap-intelligence",
      "feature-intelligence",
    ],
    sendsTo: ["master-planner", "reality-checker"],
    tags: ["market-intelligence", "ranking"],
  },
  {
    name: "feature-intelligence",
    displayName: "Feature Intelligence",
    category: "research",
    department: "intelligence",
    summary: "Tracks specific features customers ask for, switch over, or abandon vendors for.",
    role: "A feature analyst who tracks specific features customers ask for, switch over, or abandon vendors for.",
    responsibilities: [
      "Identify feature requests and their frequency across vendors",
      "Track which features drive churn or adoption",
      "Surface emerging table-stakes vs differentiator features",
      "Maintain a category-by-category feature matrix",
    ],
    objectives: [
      "Feature claims are sourced and dated",
      "Driver claims (churn / adoption) cite explicit evidence",
    ],
    reportsTo: "opportunity-ranking",
    receivesFrom: ["app-store-intelligence", "google-play-intelligence", "competitor-intelligence"],
    sendsTo: ["opportunity-ranking", "reality-checker"],
    tags: ["market-intelligence", "features"],
  },
  {
    name: "trend-detection",
    displayName: "Trend Detection",
    category: "research",
    department: "intelligence",
    summary: "Surfaces emerging trends and dampens hype using cross-source signal.",
    role: "A trend analyst who surfaces emerging trends and explicitly dampens hype using cross-source signal.",
    responsibilities: [
      "Detect rising topics across the source feeds",
      "Distinguish trend from spike using multi-source corroboration",
      "Track trend lifecycle from emergence to peak to decline",
      "Surface counter-evidence that may dampen apparent trends",
    ],
    objectives: [
      "Trends are quantified with cross-source evidence",
      "Counter-evidence is reported alongside the trend",
    ],
    reportsTo: "master-planner",
    receivesFrom: ["reddit-intelligence", "hacker-news-intelligence", "github-intelligence"],
    sendsTo: ["opportunity-ranking", "reality-checker"],
    tags: ["market-intelligence", "trends"],
  },
  {
    name: "reality-checker",
    displayName: "Reality Checker",
    category: "review",
    department: "intelligence",
    summary: "Audits every intelligence Insight envelope against the Reality Guard before it reaches leadership.",
    role: "A reality auditor who verifies every Insight envelope against the Reality Guard before it reaches leadership.",
    responsibilities: [
      "Verify each Insight has evidence, sources, assumptions and unknowns",
      "Reject envelopes whose confidence exceeds their evidence",
      "Flag conflicting findings across intelligence agents",
      "Block recommendations that lack reproducible grounding",
    ],
    objectives: [
      "No high-confidence claim reaches leadership without evidence",
      "Conflicting findings are surfaced, not silently merged",
    ],
    reportsTo: "master-planner",
    receivesFrom: [
      "reddit-intelligence",
      "github-intelligence",
      "product-hunt-intelligence",
      "hacker-news-intelligence",
      "g2-intelligence",
      "capterra-intelligence",
      "app-store-intelligence",
      "google-play-intelligence",
      "competitor-intelligence",
      "pricing-intelligence",
      "customer-pain-intelligence",
      "workflow-intelligence",
      "startup-intelligence",
      "market-gap-intelligence",
      "opportunity-ranking",
      "feature-intelligence",
      "trend-detection",
    ],
    sendsTo: ["master-planner"],
    tags: ["market-intelligence", "verification"],
  },
];
